apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
spec:
  ports:
  - name: api
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: cluster-port
    port: 8201
    protocol: TCP
    targetPort: 8201
  selector:
    app: vault
  sessionAffinity: None
  type: ClusterIP
