apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vault
  name: vault-config
data:
  config.hcl: |-
    disable_mlock = true
    api_addr = "0.0.0.0:8200"
    cluster_addr = "0.0.0.0:8201"
    ui = true

    listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/etc/tls/consul/consul.pem"
        tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA"
        tls_client_ca_file = "/etc/tls/consul/ca.pem"
        tls_disable = 0
        tls_key_file = "/etc/tls/consul/consul-key.pem"
        tls_prefer_server_cipher_suites = true
      }

    storage "consul" {
        address = "127.0.0.1:8443"
        path = "vault/"
        service = "vault"
        scheme = "https"
        tls_ca_file = "/etc/tls/consul/ca.pem"
        tls_cert_file = "/etc/tls/consul/consul.pem"
        tls_key_file = "/etc/tls/consul/consul-key.pem"
      }
